import type { WeekData } from './types'
import { asset } from './utils/assets'

const A = asset('assets/')

export const weeks: WeekData[] = [
  {
    week: 0,
    title: '开始界面音乐',
    fullTitle: '开始界面音乐',
    audio: `${A}audio/opening.mp3`,
    scene: `${A}scenes/apartment.webp`,
    hero: `${A}characters/hero0.webp`,
    threshold: 0,
    bpm: 118,
    story: '依淋PD：（冷笑）素人？泥也配参加《创造1淋1》？基本功不合格就给本公主美美吸进淋逼惹！\n主角：（咬牙切齿）这就让泥闭嘴惊艳！\n依淋PD：键盘党按 F 和 J，手机党给我狠狠戳下面的大粉垫！来，跟着节奏试敲一击！',
    choices: [],
  },
  {
    week: 1,
    title: '七十二变',
    fullTitle: '初舞台-七十二变',
    audio: `${A}audio/week1.mp3`,
    srt: `${A}audio/week1.srt`,
    scene: `${A}scenes/stage1.webp`,
    hero: `${A}characters/hero1.webp`,
    threshold: 3000,
    bpm: 126,
    story: '后台衣服被路人选手不小心弄脏。',
    choices: [
      { label: '手撕衣服，改成前卫朋克风', outcome: '全场惊呼好本质！', rewards: { looks: 15 } },
      { label: '开启淋语，嘲讽反击', outcome: '对家当场破防退赛！', rewards: { lin: 20 }, practiceDelta: 1 },
    ],
  },
  {
    week: 2,
    title: '少男杀手',
    fullTitle: '一公-少男杀手',
    audio: `${A}audio/week2.mp3`,
    srt: `${A}audio/week2.srt`,
    scene: `${A}scenes/stage2.webp`,
    hero: `${A}characters/hero2.webp`,
    threshold: 8000,
    bpm: 132,
    story: '分组遇到强抢副歌核心段落的傲慢队友。',
    choices: [
      { label: '美美隐身，极限旋转', outcome: '大艺术家不需要抢段落也是焦点！', rewards: { skill: 20 } },
      { label: '买假唱通稿，送她上热搜', outcome: '对家在后台哭着隐身了噜！', rewards: { lin: 25, fans: 10 } },
    ],
  },
  {
    week: 3,
    title: '白眼翻天',
    fullTitle: '二公-白眼翻天',
    audio: `${A}audio/week3.mp3`,
    srt: `${A}audio/week3.srt`,
    scene: `${A}scenes/stage3.webp`,
    hero: `${A}characters/hero3.webp`,
    threshold: 15000,
    bpm: 138,
    story: '录制现场遭恶意剪辑，全网黑粉围攻。',
    choices: [
      { label: '发黑红虐粉小作文', outcome: '死忠粉哭着为泥打钱！', rewards: { fans: 30 } },
      { label: '一字马打动总赞助商', outcome: '澄清加长版正片连夜播出！', rewards: { looks: 25, lin: 15 } },
    ],
  },
  {
    week: 4,
    title: '大阴阳师',
    fullTitle: '三公-大阴阳师',
    audio: `${A}audio/week4.mp3`,
    srt: `${A}audio/week4.srt`,
    scene: `${A}scenes/stage4.webp`,
    hero: `${A}characters/hero4.webp`,
    threshold: 25000,
    bpm: 144,
    story: '1V1 强力对家“纽祜禄氏”彩排现场挑衅。',
    choices: [
      { label: '连环淋语绕晕媒体', outcome: '媒体当场转铁粉！', rewards: { lin: 30, fans: 15 } },
      { label: '躲进练习室练到冒烟', outcome: '实力直接碾压一切通稿！', rewards: { skill: 30 }, practiceDelta: 2 },
    ],
  },
  {
    week: 5,
    title: '美丽极限',
    fullTitle: '半决赛-美丽极限',
    audio: `${A}audio/week5.mp3`,
    srt: `${A}audio/week5.srt`,
    scene: `${A}scenes/stage5.webp`,
    hero: `${A}characters/hero5.webp`,
    threshold: 35000,
    bpm: 148,
    story: '化妆师被对家买断，没有造型师可用。',
    choices: [
      { label: '自己化芭比粉雀斑妆', outcome: '引领时尚新潮流，本质！', rewards: { looks: 30 } },
      { label: '把拉链情报发给狗仔', outcome: '她美美隐身，泥成功借到造型！', rewards: { lin: 35 } },
    ],
  },
  {
    week: 6,
    title: '塑料王冠',
    fullTitle: '总决赛-塑料王冠',
    audio: `${A}audio/week6.mp3`,
    srt: `${A}audio/week6.srt`,
    scene: `${A}scenes/stage6.webp`,
    hero: `${A}characters/hero6.webp`,
    threshold: 50000,
    bpm: 154,
    story: '所有败者：泥也配站在这？泥以为泥是谁？赶快乖乖跪下！\n主角：（缓缓劈叉）睁大泥们的狗眼看好惹，本公主才是唯一的真大花！本质骑士，给。我。下。跪！',
    choices: [],
  },
]

export const initialStats = { looks: 0, skill: 0, lin: 0, fans: 0 }
